### ISSUE TITLE
feature request: bar plot of median for 'add_col_summary' and 'add_row_summary'

### ISSUE THREAD

**Issue by IgnatiusPang** [ropensci/iheatmapr#10]
Dear Ms. Schep,

Currently, the 'add_col_summary' and 'add_row_summary' add a bar plot to the margin of the heat map. The bar plot would indicate the mean value for each column or row, but only the mean value is available. Would it be possible to enable to the user to plot the 'median' value for the bar plot instead please? Even better, it may be useful to let the user to choose which function to use for the bar plot (e.g. sd, var, median, mad etc...).

The package is very useful and I'm already using it for my projects! Thank you! Looking forward to read the paper associated with it. 

Yours Sincerely,

Ignatius Pang

**Comment by AliciaSchep** [comment]
Hi Ignatius,

Great suggestion -- I think that'd be a nice feature to add.  I think there could be an argument that would default to the function `mean` but someone could add in their own summary function if desired, such as `median` or even a custom function. 

-Alicia

**Comment by AliciaSchep** [comment]
Actually custom summary functions might be tricky, would have to think about handling different optional arguments and validating that they actually are summary functions.  For now, I am going to add in support for 'mean','median','sd','var','mad','min', and 'max' via a `summary_function` argument.

**Comment by IgnatiusPang** [comment]
Thank you Alicia. I agree with adding support for a limited number of functions. I think having these commonly used functions will be very helpful already =)

**Comment by AliciaSchep** [comment]
Great, these options are now in iheatmapr, so closing this issue!
