### ISSUE TITLE
Deploying Shiny apps that use iheatmapr

### ISSUE THREAD

**Issue by Johnson-Stephen** [ropensci/iheatmapr#31]
Hello,

I'm currently unable to deploy a Shiny app that uses the iheatmapr package to shinyapps.io. I've been able to deploy other apps that don't use the package, and I can run apps that use iheatmapr locally. When I try to deploy, I get this error:

```
Error: Unhandled Exception: Child Task 542254620 failed: Error parsing manifest: Unable to determine package source for Bioconductor package iheatmapr: Repository must be specified
```

I'm able to replicate this error by just adding ```library(iheatmapr)``` to the old faithful geyser data shiny app. 

Thanks,

Stephen

**Comment by AliciaSchep** [comment]
Hi Stephen,

I think this may be an issue more generally with packages that have Bioconductor dependencies... Can you try the solution suggested at https://community.rstudio.com/t/failing-to-deploy-shinyapp-depending-on-bioconductor-packages/6970/2 and https://support.rstudio.com/hc/en-us/articles/226871467-Package-management-in-RStudio-Connect ?

**Comment by Tomer-Tsaban** [comment]
YES! thank you very much. this indeed works and my app is currently online including iheatmapr components. 
I think it could be useful to include a note about this process in the vingette or some place else, for users who intend to deploy an app using your great package. 

thanks again!

**Comment by AliciaSchep** [comment]
The documentation has now been updated to add a section about this use case: https://ropensci.github.io/iheatmapr/articles/full_vignettes/iheatmapr.html#deploying-on-shinyapps-io
