### ISSUE TITLE
show_colorbar not working

### ISSUE THREAD

**Issue by slfan2013** [ropensci/iheatmapr#32]
It seems these two codes provide identical result?

`main_heatmap(Indometh_patient_cor,name = "Correlation")%>%add_main_heatmap(Indometh_matrix,name = "Indometacin<br>Concentration", show_colorbar = FALSE)`

and

`main_heatmap(Indometh_patient_cor,name = "Correlation")%>%add_main_heatmap(Indometh_matrix,name = "Indometacin<br>Concentration", show_colorbar = TRUE)`

Possible reason:

`new_plot <- new("MainHeatmap",
                            xaxis = "x",
                            yaxis = yname,
                            colorbar = name,
                            show_colorbar = TRUE,
                            data = data,
                            text = text,
                            tooltip = tooltip)`

The code of `show_colorbar` is always set to be `TRUE` within the `add_main_heatmap` function.

**Comment by AliciaSchep** [comment]
Yup, thanks for identifying the source of issue... have pushed a fix to the issue.  Not sure yet when that would get updated on cran, might try to get a couple fixes/updates in before a re-release. Until then would need to use github version for correct behavior.
