### ISSUE TITLE
License / copyright information

### ISSUE THREAD

**Issue by mschilli87** [ropensci/iheatmapr#34]
The [`LICENSE` file](https://github.com/ropensci/iheatmapr/blob/e92024d897329ab12b8f686855a067d32fa55cc7/LICENSE) only contains a copyright note for the year 2017 only, though [there has been code added in 2018](https://github.com/ropensci/iheatmapr/graphs/contributors).

Also, while having this on [rOpenSci](https://github.com/ropensci) seems to imply [openness but not necessarily freedom](https://www.gnu.org/philosophy/open-source-misses-the-point.en.html), actually (re-)using this would be much easier given a proper free license. I for example would like to package `iheatmapr` for [GNU Guix](https://www.gnu.org/software/guix) to make it available on [our institute's computational infrastructure](https://guix.mdc-berlin.de/), but this requires me to specify a license.

Also, while I respect anybodies freedom to not release their software as free, I would not want to rely on software that cannot be maintained once the original author doesn't have the resources anymore. :wink:

**Comment by mschilli87** [comment]
I just remembered that R packages usually include license information in the [`DESCRIPTION` file](https://github.com/ropensci/iheatmapr/blob/master/DESCRIPTION#L45) and was very happy to see https://github.com/ropensci/iheatmapr/blob/e92024d897329ab12b8f686855a067d32fa55cc7/DESCRIPTION#L45.

I'll leave this open as I still believe the copyright should be updated and the license could/should be indicated more clearly, but I'll take this as a green light to continue packaging. :wink:

**Comment by AliciaSchep** [comment]
Yes, the license is MIT as indicated by DESCRIPTION file (agree that the standard R package way of specifying licence with the template is not the most obvious!).  I've added a 'badge' to the README to indicate the license there as well.  Have also updated the year.
