### ISSUE TITLE
iheatmapr_event not working on relayout

### ISSUE THREAD

**Issue by oristaszewski** [ropensci/iheatmapr#35]
this line in iheatmapr_event

else if (event == "iheatmapr_selected") {

should read 

else if (event == "iheatmapr_relayout") {

**Comment by mschilli87** [comment]
@oristaszewski: You can [edit `shiny.R`  on github](https://github.com/ropensci/iheatmapr/blob/master/R/shiny.R) and automatically create a pull request for that change. Use the little pen in the top-right to do so.
Also, to get the proposed change accepted, you should consider adding a short explanation *why* you think the current code is wrong and *how* your suggested change fixes this.

**Comment by oristaszewski** [comment]
thanks for the pointer and done as suggested.

**Comment by mschilli87** [comment]
For reference: https://github.com/ropensci/iheatmapr/pull/36

**Comment by AliciaSchep** [comment]
Thanks @mschilli87 and @oristaszewski, fix is merged into master branch. Thinking of trying to do a few maintenance updates & then another cran release... until then the fix will be on the master branch.
