### ISSUE TITLE
Fails with dev scales

### ISSUE THREAD

**Issue by hadley** [ropensci/iheatmapr#59]
With test failures like:

```
── 1. Failure: can add a row barplot to single horizontal heatmap (@test_barplot.R#5)  ─────────────────────────────────
Not equal to reference from `reference/row_barplot_horizontal.rds`.
Component "data": Component 1: Component 6: Component 2: Attributes: < Component 2: Lengths (162, 160) differ (string compare on first 160) >
Component "data": Component 1: Component 6: Component 2: Attributes: < Component 2: 128 string mismatches >
Component "data": Component 1: Component 6: Component 2: 6 string mismatches
```

**Comment by AliciaSchep** [comment]
Thanks for the notice, will look into this and how to fix.

**Comment by AliciaSchep** [comment]
Seems like there are two issues, (1) This package use `scales::muted` to get default colors (function now gives slightly different result), which was pretty silly choice, can easily change to just use the output of the function, (2) the results of `scales::col_numeric` have changed.  Will need to think about how to adjust this one... right now the tests look for entire charts to be recreated exactly, which is fairly brittle.  Probably good idea to rework those expectations to look for an approximately equal json-as-list representation of the chart.  Wondering if there is an existing "approximately equal" for colors?

**Comment by hadley** [comment]
One option might be to use [vdiffr](http://vdiffr.r-lib.org)? That's what we use for testing ggplot2.

**Comment by AliciaSchep** [comment]
Thanks for the suggestion, I think in long run switching to use vdiffr would be a good idea, but I think it would first require enabling outputting an svg (also a worthwhile feature in its own right).  Will try going with a work-around (checking scales package version, and having two different versions of output) for now.

**Comment by AliciaSchep** [comment]
I have submitted to cran now an updated version that should work with both old & new versions of scales (using a hacky approach of looking for package version). Will close this issue once that is up on cran, and will add a new issue for better testing approach.

**Comment by hadley** [comment]
Thanks!

**Comment by mschilli87** [comment]
@AliciaSchep:
> I have submitted to cran now an updated version...

Would you mind tagging/releasing this version on github, too? (see https://github.com/ropensci/iheatmapr/issues/44).

**Comment by AliciaSchep** [comment]
@mschilli87 I will tag/release once it is accepted on CRAN.  

(Ran into an issue where there was a pre-existing issue with the package on the 'noLD' platform.  The fix for this scales issue actually ended up helping a bit for that issue, but did not fully resolve it. Have a fix now and should submit a new release soon).

**Comment by AliciaSchep** [comment]
Updated version on CRAN now and made a tag/release on github.
