### ISSUE TITLE
Remove legends from the app

### ISSUE THREAD

**Issue by shreyagupta0909** [ropensci/iheatmapr#63]
We are using iheatmapr and we want to remove the legends from the app. 
Before the package was updated we were able to remove the legends but now it seems the functionality is not working.

**Comment by AliciaSchep** [comment]
Thanks for opening an issue -- can you please provide an example? Ideally reproducible?  And also specify the package version you are using.  If you're referring to the `show_colorbar` argument, as far as I can tell it is still working with the latest version of `main_heatmap` and `iheatmap`.

**Comment by shreyagupta0909** [comment]
We are able to readjust the position of the legends using the following:

mat <- matrix(rnorm(20), ncol = 5, nrow = 4)  
hm <- main_heatmap(mat
                   ,colorbar_grid = setup_colorbar_grid(nrows = -2, y_length =0
                                                        ,x_spacing =0, y_spacing = 0,
                                                        x_start =0,y_start = -1) )


But we would like to remove it. The show_colorbar argument is left unused.

hm <- main_heatmap(mat
                   ,colorbar_grid = setup_colorbar_grid(nrows = -2, y_length =0
                                                        ,x_spacing =0, y_spacing = 0,
                                                        x_start =0,y_start = -1),show_colorbar=F )

Error in .local(data, ...) : unused argument (show_colorbar = F)


[SessionInfo.txt](https://github.com/ropensci/iheatmapr/files/3886114/SessionInfo.txt)

**Comment by AliciaSchep** [comment]
Thanks for the example and session info -- Please try updating to version 0.4.12 (either via CRAN or install_github); it should have fixed this bug.

**Comment by shreyagupta0909** [comment]
Thank you.. this worked.
