### ISSUE TITLE
Plotting one column or row fails

### ISSUE THREAD

**Issue by romert01** [ropensci/iheatmapr#69]
If for some reason I'd like to plot one single row or column, the fill is always just white:

```
a <- matrix(c(1, 2, 3, 4), nrow = 2)
b <- matrix(c(1, 2), nrow = 2)
d <- matrix(c(1, 2), nrow = 1)

iheatmap(a) ## This works fine
```
![image](https://user-images.githubusercontent.com/51340354/80038321-6cf97b80-84c3-11ea-8a9f-132b8750aaa6.png)

```
iheatmap(b) # This fails
```
![image](https://user-images.githubusercontent.com/51340354/80038390-8d293a80-84c3-11ea-8de9-1ce5812df55c.png)

 ```
iheatmap(d)  # This also fails
```
![image](https://user-images.githubusercontent.com/51340354/80038362-7c78c480-84c3-11ea-99ec-cefd257b5bb4.png)

**Comment by AliciaSchep** [comment]
Thanks for the reproducible example.  Found the root cause for this (single length vector getting "unboxed" in json conversion into a single digit instead of array) and am implementing a fix that should go into next cran release.
