### ISSUE TITLE
could not find function 'to_widget' 

### ISSUE THREAD

**Issue by whtns** [ropensci/iheatmapr#71]
I am using iheatmapr in a shiny app created by calling a package function. I am unable to run renderIheatmap or iheatmaprOutput without explicitly loading the package. instead I receive the title error message. 

here's a reprex where the behavior can be replicating by excluding `library(iheatmapr)`

```
library(shiny)
# library(iheatmapr)

if (interactive()) {
  options(device.ask.default = FALSE)
  
  # The object can be passed to runApp()
  app <- shinyApp(
    ui = fluidPage(
      numericInput("n", "n", 1),
      iheatmapr::iheatmaprOutput("heatmap")
    ),
    server = function(input, output) {
      output$heatmap <- iheatmapr::renderIheatmap( iheatmapr::iheatmap(as.matrix(cars)))
    }
  )
  
  runApp(app)
}
```

**Comment by olobiolo** [comment]
I am having the same problem.

**Comment by daattali** [comment]
This is still an ongoing issue. The package must be explicitly attached in order to use it in shiny, which isn't great in large apps

**Comment by olobiolo** [comment]
@daattali Indeed, that is why I raised the issue and what I have been doing so far. Thanks for pointing to the workaround though.

**Comment by AliciaSchep** [comment]
I think #82 should fix this issue; at least it seems to resolve the problem for the example above.

**Comment by daattali** [comment]
Confirmed this is fixed!

**Comment by olobiolo** [comment]
Thank you!
