### ISSUE TITLE
CRAN deprecation

### ISSUE THREAD

**Issue by ahmohamed** [ropensci/iheatmapr#96]
Hi @AliciaSchep,

I wanted to clarify what is the plan for iheatmapr after it was removed from CRAN. I can see the latest test results are WARNINGs on linux platforms. I maintain a Bioconductor package that *suggests* iheatmapr, and I'm keen to see this package continue to be available.

Cheers,
Ahmed.

**Comment by ahmohamed** [comment]
@AliciaSchep kindly following up on this issue from last week. It would be great to know (at least roughly) what are the next steps for this package, so I can plan accordingly.

**Comment by AliciaSchep** [comment]
hi @ahmohamed thanks for raising.  I'll look into the issues & see if a quick fix is possible, but can't promise anything re timeline
